### ISSUE TITLE
No `spring-chatting-server_` prefix is setted

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#105]
## **Description**

When running current docker compose build, we can build images as below. Here we can see that no `spring-chatting-server_` prefix is setted!

```
api-server                                    latest                48282233a336   20 seconds ago   384MB
customer-server                               latest                d823a09e3a32   24 seconds ago   427MB
chatting-server                               latest                b0098ed98fcf   31 seconds ago   431MB
user-server                                   latest                57c0356c9156   38 seconds ago   439MB
discovery-server                              latest                701e82141984   43 seconds ago   378MB
configuration-server                          latest                08317650c3c6   48 seconds ago   385MB
```

I forgot how the `image` step works.

When we compose build with below code, the build image name will be `configuration-server` and tag will be `latest` 👍

```yaml
  configuration-server:
    container_name: configuration-server
    build:
      context: ./config-service
      dockerfile: Dockerfile
    image: configuration-server:latest
    expose:
      - 8888
    ports:
      - "8888:8888"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      spring_cloud_config_server_git_uri: https://github.com/ghkdqhrbals/spring-chatting-server
    depends_on:
      - rabbitmq
    restart: always
```

That means we have to add `spring-chatting-server_` prefix here! **Because since we running this build in git actions, environment also has multiple docker files. So we need to distinguish images that is ours or git actions'.**

Rather just set prefix as `spring-chatting-server_`, `main-service_` will be more appropriate!
