### ISSUE TITLE
Error occured cloning to base directory with Connection Timeout

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#15]
When cloning repository for bootstrapping app-dev.yaml in each services, `connection timeout` error occured!

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/29156882/235348404-da7e227d-05ac-4655-98db-e4fdc31b6523.png">

**Comment by ghkdqhrbals** [comment]
For bigger scale,

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/29156882/235348426-7cef0b69-738a-42d4-b313-80c1def16dcb.png">

**Comment by ghkdqhrbals** [comment]
# Solved

by adding `spring_cloud_config_server_git_uri: https://github.com/ghkdqhrbals/spring-chatting-server.git` in compose file

```yaml
  configuration-server:
    container_name: configuration-server
    build: ./config-service
    ports:
      - "8888:8888"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      spring_cloud_config_server_git_uri: https://github.com/ghkdqhrbals/spring-chatting-server.git
    depends_on:
      - rabbitmq
    restart: always
```
