### ISSUE TITLE
Ransomeware Attack

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#180]
## Desciprtion

```
All your data is backed up. You must pay 0.01 BTC to 14PYVptPexgRpHRm7SSrFMAyBKYymkRA55 In 48 hours, your data will be publicly disclosed and deleted. (more information: go to http://iplis.ru/data3)
```

Today, I accessed to db table and this message was stored in db. Well, since my db has been exposed with password, id in this github code, It was going to happen someday.

Now, I will store password and key in AWS SECRET, and also stop exposing my db in public.

**Comment by ghkdqhrbals** [comment]
## To hiding secrets
> This shouldn't be pushed to public repository

1. Hashing original secrets

* `echo -n "{your_original_secret}" | sha256sum`

2. Encoding `hashed_secrets` into base64
* echo "{HASH(your_original_secret)}" | base64

3. Adding base64 encoded hashed secrets to Secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  user-db-username: {user-db-username}
  user-db-password: {user-db-password}
  chat-db-username:{chat-db-username}
  chat-db-password: {chat-db-password}
  customer-db-username: {customer-db-username}
  customer-db-password: {customer-db-password}
```
