### ISSUE TITLE
[Document] Slack alert enabled

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#191]
## Desciprtion

* Add Slack deploy workflow job

```yaml
  ...
  pushSlack:
    needs: pushNewTag
    name: Slack Alert
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

```

* Result of slack alert job

<img width="1410" alt="image" src="https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/f1a45ec5-1f1e-4633-ae20-c73503cca9c8">

<img width="620" alt="image" src="https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/ad8643b0-4c72-45e5-8562-0fdd2d4e2adb">
