### ISSUE TITLE
How to configure PV and PVC in AWS-EKS cluster?

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#269]
Since I bound chat db pv and pvc with gp2 storageclass, it still doesn't work :(
<img width="572" alt="image" src="https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/6ad803e3-7a74-49bd-930a-637c3ba836a2">
<img width="952" alt="image" src="https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/04f2e2aa-843e-492d-a94a-237737b68d58">

**Comment by ghkdqhrbals** [comment]
## Problem

Since I run pvc without storageClassName, AWS-EKS automatically set my pvc with **gp2** storageClassName which is AWS-EBS basic name.

Typically, when using a storage type like **NFS**, you define the PV directly, reference it to the PVC, and **do not use a StorageClass**.

> StorageClass is primarily used to dynamically provision block storage provided by cloud providers (e.g. AWS, GCP, Azure). Network file systems such as NFS typically do not support dynamic provisioning and require PVs to be set up and managed in advance.

## Solved

* Setting the NFS PV's storageClassName to an empty string ("") indicates that the StorageClass is not used.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""    # Set empty string like this
```

* Set private VPC network subnet in `/etc/exports`
  * `/nfs_shared 172.31.1.0/16(rw,sync,no_root_squash,no_subtree_check)`
