### ISSUE TITLE
[Bug] Nginx rewrite path regex error

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#293]
## **Description**

* Code
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "www.litcodev.com"
      http:
        paths:
          - path: /api(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-server-service
                port:
                  number: 8010
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: front-server-service
                port:
                  number: 8080
```
* Check actual path

<img width="1087" alt="image" src="https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/d5eddd18-77d1-40dc-9678-63891f8414d1">

As you can see, `https://www.litcodev.com/api/health-check` is turned into `https://www.litcodev.com//health-check` which only exclude `api` not `/api`

So `/api(.*)` regex will be changed to `/api/(.*)`
