### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#3]
initial setup
```
POST http://localhost:8091/connectors
{
    "name": "chatting-5433-connector",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "task.max" : 1,
        "topics": "dbserver5434.public.user_table",
        
        "connection.url": "jdbc:postgresql://chatting-db-1:5433/chat",
        "connection.user":"postgres",
        "connection.password":"password",

        "insert.mode":"upsert",

        "table.name.format":"chat.user_table",

        "batch.size": "1"
    }
}   
```

And when data was passed db from kafka, error occured

> org.apache.kafka.connect.errors.ConnectException: Sink connector 'chatting-5433-connector' is configured with 'delete.enabled=false' and 'pk.mode=none' and therefore requires records with a non-null Struct value and non-null Struct schema, but found record at (topic='dbserver5434.public.user_table',partition=0,offset=0,timestamp=1672986550637) with a HashMap value and null value schema

**Comment by ghkdqhrbals** [comment]
I change my Docker-compose file and configuration setting

## Docker-compose.yaml
```
  kafka-connect:
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect
    ports:
      - "8091:8083"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - chatting-db-1
      - chatting-db-2
      - auth-db
      - zookeeper
    environment:
      LOG_LEVEL: DEBUG
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: __pg.sink.config.storage
      CONNECT_STATUS_STORAGE_TOPIC: __pg.sink.status.storage
      CONNECT_OFFSET_STORAGE_TOPIC: __pg.sink.offset.storage
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_REST_PORT: 8091
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
    command:
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.6.1
        confluent-hub install --no-prompt confluentinc/connect-transforms:1.4.3
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
```

## configuration
```
{
    "name": "chatting-5433-connector",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "task.max" : 1,
        "topics": "dbserver5434.public.user_table",
        "insert.mode": "upsert",
        "tombstones.on.delete": "true",
        
        "connection.url": "jdbc:postgresql://chatting-db-1:5433/chat",
        "connection.user":"postgres",
        "connection.password":"password",

        "table.name.format":"user_table",

        "batch.size": "1"
    }
}   
```

And after adding data in my 5434 database, I got another Errors :(

```
kafka-connect             | [2023-01-06 07:54:19,267] ERROR WorkerSinkTask{id=chatting-5433-connector-3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
kafka-connect             | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
kafka-connect             | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:223)
kafka-connect             | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
kafka-connect             | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect             | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect             | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka-connect             | Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic dbserver5434.public.user_table to Avro: 
kafka-connect             | 	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:124)
kafka-connect             | 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:88)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
kafka-connect             | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
kafka-connect             | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
kafka-connect             | 	... 13 more
kafka-connect             | Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
kafka-connect             | 	at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.getByteBuffer(AbstractKafkaSchemaSerDe.java:244)
kafka-connect             | 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer$DeserializationContext.<init>(AbstractKafkaAvroDeserializer.java:334)
kafka-connect             | 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:202)
kafka-connect             | 	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:172)
kafka-connect             | 	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)
kafka-connect             | 	... 17 more
```

**Comment by ghkdqhrbals** [comment]
I remove schema in docker-compose

```
  kafka-connect:
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect
    ports:
      - "8091:8083"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - chatting-db-1
      - chatting-db-2
      - auth-db
      - zookeeper
    environment:
      LOG_LEVEL: DEBUG
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: __pg.sink.config.storage
      CONNECT_STATUS_STORAGE_TOPIC: __pg.sink.status.storage
      CONNECT_OFFSET_STORAGE_TOPIC: __pg.sink.offset.storage
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_SCHEMAS_ENABLE: "false"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
    command:
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run
```

Heres another error...


```
ERROR WorkerSinkTask{id=chatting-5433-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Cannot ALTER TABLE "user_table" to add missing field SinkRecordField{schema=Schema{io.debezium.connector.postgresql.Source:STRUCT}, name='source', isPrimaryKey=false}, as the field is not optional and does not have a default value (org.apache.kafka.connect.runtime.WorkerSinkTask)
kafka-connect             | io.confluent.connect.jdbc.sink.TableAlterOrCreateException: Cannot ALTER TABLE "user_table" to add missing field SinkRecordField{schema=Schema{io.debezium.connector.postgresql.Source:STRUCT}, name='source', isPrimaryKey=false}, as the field is not optional and does not have a default value
kafka-connect             | 	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:182)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:83)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:122)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
kafka-connect             | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect             | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect             | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka-connect             | [2023-01-06 08:44:28,216] ERROR WorkerSinkTask{id=chatting-5433-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
kafka-connect             | org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
kafka-connect             | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect             | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect             | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect             | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka-connect             | Caused by: io.confluent.connect.jdbc.sink.TableAlterOrCreateException: Cannot ALTER TABLE "user_table" to add missing field SinkRecordField{schema=Schema{io.debezium.connector.postgresql.Source:STRUCT}, name='source', isPrimaryKey=false}, as the field is not optional and does not have a default value
kafka-connect             | 	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:182)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:83)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:122)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
kafka-connect             | 	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
kafka-connect             | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
kafka-connect             | 	... 10 more
```
