### ISSUE TITLE
[Document] 채팅서버 HPA 적용 시 API error 증가

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#317]
![image](https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/5aa130eb-07d7-4682-ba0e-dec15a15075a)

HPA 로 채팅서버 cpu 사용량에 맞춰 자동으로 스케일아웃 하였을 때, 스케일 아웃이 안정화되는 시간동안 에러가 다량 발생하였습니다. 초기 init 될 때 동안 서비스가 라운드 로빈으로 자동 LB 를 진행하면서 그대로 트래픽을 전달했기 때문에 발생한 에러로 보여요.

이를 해결하기 위해서는 **채팅서버의 health check 이 후** service 가 트래픽을 전달하는 기능이 필요합니다. 이 부분은 `readinessProbe` 를 통해 해결할 수 있겠네요.

이를 위해 간단한 컨트롤러를 만들겠습니다.

```java
@Slf4j
@RestController
@AllArgsConstructor
public class HealthCheckController {
    @GetMapping("/health")
    public String healthCheck() {
        return "OK";
    }
}
```

그리고 chat-deployment.yaml 에 readinessProbe 를 아래와 같이 추가해줍니다.

```yaml
readinessProbe:
  httpGet:
    path: /health
    port: 8030
  initialDelaySeconds: 5
  periodSeconds: 5
```

만약 Spring actuator 을 사용한다면, 아래와 같이 단순 yaml 를 수정하는것만으로도 health 나 여러 정보들을 오픈할 수 있게됩니다.
```yaml
management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, httpexchanges, beans, busrefresh, prometheus
```

위와 같이 actuator 를 추가하게 된다면 path 를 /actuator/health 로 변경하면 됩니다!
